name: sql_crdt
description: Base package for Conflict-free Replicated Data Types (CRDTs) using SQL databases
version: 3.0.2
homepage: https://github.com/cachapa/sql_crdt
repository: https://github.com/cachapa/sql_crdt
issue_tracker: https://github.com/cachapa/sql_crdt/issues

environment:
  sdk: ^3.0.0

dependencies:
  crdt: ^5.1.3
#    path: ../crdt
  source_span: ^1.10.0
  sqlparser: ^0.39.2
  collection: ^1.19.1

dev_dependencies:
  lints: any
  test: any
