name: sql_crdt
description: Base package for Conflict-free Replicated Data Types (CRDTs) using SQL databases
version: 1.1.0
homepage: https://github.com/cachapa/sql_crdt
repository: https://github.com/cachapa/sql_crdt
issue_tracker: https://github.com/cachapa/sql_crdt/issues

environment:
  sdk: '^3.0.0'

dependencies:
  sqlparser: ^0.30.3
  uuid: ^3.0.7

dev_dependencies:
  lints: any
  test: any
